### ISSUE TITLE
Headset Microphone

### ISSUE THREAD

**Issue by Razvi99** [kevinshroff/KSMRD-Modded-Realtek-Audio-Drivers#7] opened 2018-10-16 14:26 UTC
Is there any way to enable the use of a headset microphone instead of the built-in one on a xps 15 9570?

**Comment by troygiorshev** [comment] 2018-11-12 17:14
Duplicate of #5 

TL;DR: No
> requires having Waves MaxxAudio which is what we're trying to get rid of in the first place. Currently no solution for this, but @kevinshroff might try and tackle it in the future.

**Closed** 2018-11-13 21:13 UTC
